import type { ImportWoLC } from "./import-wo-lc-types";

export const importWoLCs: ImportWoLC[] = [
  {
    id: "iwl-001",
    reference: "IWL-2026-00042",
    mode: "Documentary Collection - DP",
    applicant: { name: "Apex Industries Ltd.", address: "12 Industrial Zone, Dhaka", country: "Bangladesh" },
    supplier: { name: "Yamato Steel Trading", address: "5-2 Marunouchi, Tokyo", country: "Japan", bank: "MUFG Bank" },
    remittingBank: "MUFG Bank, Tokyo",
    collectingBank: "TradeFlow Bank, Dhaka",
    currency: "USD",
    invoiceAmount: 128500,
    paidAmount: 0,
    invoiceDate: "2026-04-18",
    invoiceNumber: "YST-INV-7741",
    blDate: "2026-04-22",
    blNumber: "MOLU-884512",
    goods: "Hot-rolled steel coils, 240MT",
    hsCode: "7208.27",
    incoterm: "CFR Chittagong",
    countryOfOrigin: "Japan",
    portOfLoading: "Yokohama",
    portOfDischarge: "Chittagong",
    status: "Lodged",
    documents: [
      { id: "d1", name: "Commercial_Invoice.pdf", type: "Invoice", uploadedAt: "2026-04-25", uploadedBy: "MUFG", version: 1, size: "212 KB", ocrConfidence: 0.97 },
      { id: "d2", name: "Bill_of_Lading.pdf", type: "BL", uploadedAt: "2026-04-25", uploadedBy: "MUFG", version: 1, size: "188 KB", ocrConfidence: 0.94 },
      { id: "d3", name: "Packing_List.pdf", type: "Packing List", uploadedAt: "2026-04-25", uploadedBy: "MUFG", version: 1, size: "76 KB" },
    ],
    discrepancies: [
      { id: "x1", type: "Late presentation", severity: "Medium", remarks: "Documents lodged 8 days after BL date.", status: "Open" },
    ],
    compliance: [
      { id: "c1", party: "Yamato Steel Trading", type: "Sanctions", result: "Clear", checkedAt: "2026-04-26" },
      { id: "c2", party: "MUFG Bank", type: "AML", result: "Clear", checkedAt: "2026-04-26" },
    ],
    swiftMessages: [
      { id: "s1", type: "MT202", status: "Queued", createdAt: "2026-04-27", reference: "IWL-2026-00042" },
    ],
    approvals: [
      { level: 1, role: "Maker", user: "R. Ahmed", status: "Approved", actedAt: "2026-04-26" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Pending" },
    ],
    audit: [
      { id: "a1", user: "R. Ahmed", action: "Documents lodged", timestamp: "2026-04-25 11:24" },
      { id: "a2", user: "AI Engine", action: "Discrepancy detected: Late presentation", timestamp: "2026-04-25 11:25" },
    ],
    imp: { reference: "IMP-2026-7142", amount: 128500, status: "Filed", createdAt: "2026-04-25" },
    charges: [
      { label: "Collection commission (0.15%)", amount: 192.75 },
      { label: "SWIFT charges", amount: 30 },
      { label: "Postage", amount: 18 },
    ],
    forexDeal: { rate: 119.85, dealId: "FX-88321", bookedAt: "2026-04-26" },
  },
  {
    id: "iwl-002",
    reference: "IWL-2026-00051",
    mode: "Documentary Collection - DA",
    applicant: { name: "Lumen Pharma Ltd.", address: "Plot 14, Tongi", country: "Bangladesh" },
    supplier: { name: "Bayer AG", address: "Kaiser-Wilhelm-Allee, Leverkusen", country: "Germany", bank: "Deutsche Bank" },
    remittingBank: "Deutsche Bank, Frankfurt",
    collectingBank: "TradeFlow Bank, Dhaka",
    currency: "EUR",
    invoiceAmount: 96400,
    paidAmount: 0,
    invoiceDate: "2026-03-10",
    invoiceNumber: "BAY-INV-22118",
    blDate: "2026-03-15",
    blNumber: "HLCU-771204",
    dueDate: "2026-06-13",
    tenorDays: 90,
    goods: "Pharmaceutical APIs (Sotorasib intermediates)",
    hsCode: "2933.99",
    incoterm: "CIP Dhaka",
    countryOfOrigin: "Germany",
    portOfLoading: "Hamburg",
    portOfDischarge: "Dhaka (Air)",
    status: "Accepted",
    documents: [
      { id: "d1", name: "Invoice_BAY_22118.pdf", type: "Invoice", uploadedAt: "2026-03-22", uploadedBy: "Deutsche Bank", version: 1, size: "164 KB" },
      { id: "d2", name: "AWB_77120.pdf", type: "BL", uploadedAt: "2026-03-22", uploadedBy: "Deutsche Bank", version: 1, size: "92 KB" },
      { id: "d3", name: "CoA.pdf", type: "Certificate", uploadedAt: "2026-03-22", uploadedBy: "Deutsche Bank", version: 1, size: "210 KB" },
    ],
    discrepancies: [],
    compliance: [
      { id: "c1", party: "Bayer AG", type: "Dual-Use Goods", result: "Clear", checkedAt: "2026-03-23" },
    ],
    swiftMessages: [],
    approvals: [
      { level: 1, role: "Maker", user: "N. Sultana", status: "Approved", actedAt: "2026-03-23" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-03-23" },
    ],
    audit: [
      { id: "a1", user: "N. Sultana", action: "Acceptance recorded for usance bill", timestamp: "2026-03-23 09:11" },
    ],
    imp: { reference: "IMP-2026-7204", amount: 96400, status: "Filed", createdAt: "2026-03-23" },
    charges: [
      { label: "Acceptance commission (0.20%)", amount: 192.8 },
      { label: "SWIFT charges", amount: 30 },
    ],
  },
  {
    id: "iwl-003",
    reference: "IWL-2026-00067",
    mode: "Advance Payment / TT",
    applicant: { name: "Greenfield Agro Ltd.", address: "Bogura", country: "Bangladesh" },
    supplier: { name: "Hubei Fertilizer Co.", address: "Wuhan", country: "China", bank: "ICBC" },
    currency: "USD",
    invoiceAmount: 42800,
    paidAmount: 42800,
    invoiceDate: "2026-04-02",
    invoiceNumber: "HFC-PI-3309",
    goods: "Urea, 1000MT (advance against PI)",
    hsCode: "3102.10",
    incoterm: "FOB Shanghai",
    countryOfOrigin: "China",
    portOfLoading: "Shanghai",
    portOfDischarge: "Mongla",
    status: "Paid",
    documents: [
      { id: "d1", name: "Proforma_Invoice.pdf", type: "PI", uploadedAt: "2026-04-02", uploadedBy: "M. Hasan", version: 1, size: "88 KB" },
    ],
    discrepancies: [],
    compliance: [
      { id: "c1", party: "Hubei Fertilizer Co.", type: "Sanctions", result: "Clear", checkedAt: "2026-04-03" },
    ],
    swiftMessages: [
      { id: "s1", type: "MT202", status: "ACK", createdAt: "2026-04-04", reference: "TT-7782" },
    ],
    approvals: [
      { level: 1, role: "Maker", user: "M. Hasan", status: "Approved", actedAt: "2026-04-03" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-04-03" },
    ],
    audit: [
      { id: "a1", user: "M. Hasan", action: "TT remittance executed", timestamp: "2026-04-04 10:02" },
    ],
    imp: { reference: "IMP-2026-7298", amount: 42800, status: "Reported", createdAt: "2026-04-04" },
    remittance: { utr: "TFB2026040400284", channel: "MT202", amount: 42800, sentAt: "2026-04-04", status: "Settled" },
    charges: [
      { label: "TT commission", amount: 64.2 },
      { label: "SWIFT charges", amount: 35 },
    ],
    forexDeal: { rate: 121.5, dealId: "FX-88477", bookedAt: "2026-04-04" },
  },
  {
    id: "iwl-004",
    reference: "IWL-2026-00079",
    mode: "Open Account",
    applicant: { name: "Nimbus Apparels Ltd.", address: "Gazipur", country: "Bangladesh" },
    supplier: { name: "Tex Trims Vietnam", address: "Ho Chi Minh City", country: "Vietnam" },
    currency: "USD",
    invoiceAmount: 18750,
    paidAmount: 0,
    invoiceDate: "2026-02-12",
    invoiceNumber: "TTV-2026-118",
    dueDate: "2026-04-13",
    tenorDays: 60,
    goods: "Garment trims & accessories",
    hsCode: "5806.32",
    incoterm: "FCA HCM",
    countryOfOrigin: "Vietnam",
    portOfLoading: "Ho Chi Minh",
    portOfDischarge: "Chittagong",
    status: "Overdue",
    documents: [],
    discrepancies: [
      { id: "x1", type: "Payment overdue", severity: "High", remarks: "21 days past due date.", status: "Open" },
    ],
    compliance: [],
    swiftMessages: [],
    approvals: [],
    audit: [
      { id: "a1", user: "AI Engine", action: "Overdue alert raised", timestamp: "2026-04-14 06:00" },
    ],
    imp: { reference: "IMP-2026-7102", amount: 18750, status: "Pending", createdAt: "2026-02-15" },
    charges: [],
  },
];
export function getImportWoLC(id: string) {
  return importWoLCs.find((l) => l.id === id);
}
