import type { Guarantee } from "./guarantee-types";

export const guarantees: Guarantee[] = [
  {
    id: "g-001",
    reference: "BG-2026-00118",
    type: "Performance Guarantee",
    applicant: { name: "Apex Construction Ltd.", address: "Banani, Dhaka", country: "Bangladesh" },
    beneficiary: { name: "Roads & Highways Department", address: "Tejgaon, Dhaka", country: "Bangladesh" },
    issuingBank: "TradeFlow Bank, Dhaka",
    currency: "BDT",
    amount: 18500000,
    marginPercent: 10,
    marginAmount: 1850000,
    issueDate: "2026-02-15",
    expiryDate: "2027-02-14",
    claimExpiryDate: "2027-05-14",
    status: "Issued",
    purpose: "Performance security for Dhaka–Mawla Road resurfacing contract.",
    underlyingContract: "RHD/CTG-2026/441",
    documents: [
      { id: "d1", name: "Application_Form.pdf", type: "Other", uploadedAt: "2026-02-10", uploadedBy: "Maker", version: 1, size: "112 KB" },
      { id: "d2", name: "Counter_Indemnity.pdf", type: "Other", uploadedAt: "2026-02-12", uploadedBy: "Maker", version: 1, size: "76 KB" },
    ],
    compliance: [{ id: "c1", party: "Apex Construction Ltd.", type: "AML", result: "Clear", checkedAt: "2026-02-12" }],
    swiftMessages: [{ id: "s1", type: "MT760", status: "ACK", createdAt: "2026-02-15", reference: "BG-2026-00118" }],
    approvals: [
      { level: 1, role: "Maker", user: "R. Ahmed", status: "Approved", actedAt: "2026-02-12" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-02-13" },
      { level: 3, role: "Branch Manager", user: "F. Iqbal", status: "Approved", actedAt: "2026-02-14" },
    ],
    audit: [{ id: "a1", user: "S. Karim", action: "Guarantee issued via MT760", timestamp: "2026-02-15 10:14" }],
    charges: [
      { label: "Issuance commission (1.0% p.a.)", amount: 185000 },
      { label: "SWIFT charges", amount: 1500 },
      { label: "Stamp duty", amount: 2000 },
    ],
    amendments: [],
  },
  {
    id: "g-002",
    reference: "BG-2026-00132",
    type: "Bid Bond",
    applicant: { name: "Lumen Power Engineering", address: "Uttara, Dhaka", country: "Bangladesh" },
    beneficiary: { name: "Bangladesh Power Development Board", address: "Motijheel, Dhaka", country: "Bangladesh" },
    issuingBank: "TradeFlow Bank, Dhaka",
    currency: "BDT",
    amount: 4200000,
    marginPercent: 5,
    marginAmount: 210000,
    issueDate: "2026-04-01",
    expiryDate: "2026-07-31",
    status: "Issued",
    purpose: "Bid security for 25MW solar tender (BPDB/T-225).",
    underlyingContract: "BPDB/T-225",
    documents: [],
    compliance: [{ id: "c1", party: "BPDB", type: "Sanctions", result: "Clear", checkedAt: "2026-04-01" }],
    swiftMessages: [],
    approvals: [{ level: 1, role: "Maker", user: "N. Sultana", status: "Approved", actedAt: "2026-04-01" }],
    audit: [{ id: "a1", user: "N. Sultana", action: "Bid bond issued (paper)", timestamp: "2026-04-01 12:30" }],
    charges: [{ label: "Issuance commission", amount: 14000 }, { label: "Stamp", amount: 500 }],
    amendments: [],
  },
  {
    id: "g-003",
    reference: "APG-2026-00088",
    type: "Advance Payment Guarantee",
    applicant: { name: "Padma Bridge Contractors JV", address: "Mawa, Munshiganj", country: "Bangladesh" },
    beneficiary: { name: "Bridge Authority of Bangladesh", address: "Banani, Dhaka", country: "Bangladesh" },
    issuingBank: "TradeFlow Bank, Dhaka",
    currency: "USD",
    amount: 2850000,
    marginPercent: 15,
    marginAmount: 427500,
    issueDate: "2026-01-22",
    expiryDate: "2027-01-21",
    status: "Amended",
    purpose: "Advance payment guarantee against 10% mobilisation advance.",
    underlyingContract: "BAB/PB-Spur/2026/02",
    documents: [],
    compliance: [{ id: "c1", party: "BAB", type: "Sanctions", result: "Clear", checkedAt: "2026-01-22" }],
    swiftMessages: [
      { id: "s1", type: "MT760", status: "ACK", createdAt: "2026-01-22", reference: "APG-2026-00088" },
      { id: "s2", type: "MT767", status: "Sent", createdAt: "2026-04-10", reference: "APG-2026-00088/A1" },
    ],
    approvals: [{ level: 1, role: "Maker", user: "M. Hasan", status: "Approved" }, { level: 2, role: "Checker", user: "S. Karim", status: "Approved" }],
    audit: [
      { id: "a1", user: "M. Hasan", action: "APG issued", timestamp: "2026-01-22 10:14" },
      { id: "a2", user: "S. Karim", action: "Amendment A1: amount reduced after 30% recovery", timestamp: "2026-04-10 14:50" },
    ],
    charges: [{ label: "Issuance commission (1.5% p.a.)", amount: 42750 }, { label: "Amendment commission", amount: 250 }],
    amendments: [
      { id: "am1", field: "Amount", oldValue: "USD 2,850,000", newValue: "USD 1,995,000", status: "Approved", requestedAt: "2026-04-08" },
    ],
  },
  {
    id: "g-004",
    reference: "SBL-2026-00021",
    type: "Standby LC",
    applicant: { name: "Greenfield Trading Ltd.", address: "Gulshan, Dhaka", country: "Bangladesh" },
    beneficiary: { name: "Glencore International AG", address: "Baar, Switzerland", country: "Switzerland", bank: "UBS" },
    issuingBank: "TradeFlow Bank, Dhaka",
    advisingBank: "UBS, Zurich",
    currency: "USD",
    amount: 1200000,
    marginPercent: 25,
    marginAmount: 300000,
    issueDate: "2026-03-05",
    expiryDate: "2027-03-04",
    status: "Invoked",
    purpose: "SBLC supporting open-account commodity purchases.",
    documents: [],
    compliance: [{ id: "c1", party: "Glencore International AG", type: "Sanctions", result: "Clear", checkedAt: "2026-03-04" }],
    swiftMessages: [{ id: "s1", type: "MT760", status: "ACK", createdAt: "2026-03-05", reference: "SBL-2026-00021" }],
    approvals: [{ level: 1, role: "Maker", user: "K. Hossain", status: "Approved" }, { level: 2, role: "Checker", user: "S. Karim", status: "Approved" }],
    audit: [
      { id: "a1", user: "K. Hossain", action: "SBLC issued via MT760", timestamp: "2026-03-05 09:00" },
      { id: "a2", user: "Glencore (UBS)", action: "Invocation notice received for USD 320,000", timestamp: "2026-04-22 16:18" },
    ],
    charges: [{ label: "Issuance commission (2.0% p.a.)", amount: 24000 }, { label: "SWIFT", amount: 60 }],
    amendments: [],
    invocations: [{ id: "inv1", amount: 320000, receivedAt: "2026-04-22", status: "Under Review", remarks: "Documents under examination — 5-day TAT." }],
  },
];

export function getGuarantee(id: string) {
  return guarantees.find((g) => g.id === id);
}