import type { ExportWoLC } from "./export-wo-lc-types";

export const exportWoLCs: ExportWoLC[] = [
  {
    id: "ewl-001",
    reference: "EWL-2026-00031",
    mode: "Documentary Collection - DP",
    exporter: { name: "Bengal Knit Composite Ltd.", address: "Savar EPZ, Dhaka", country: "Bangladesh" },
    buyer: { name: "H&M Hennes & Mauritz", address: "Mäster Samuelsgatan, Stockholm", country: "Sweden", bank: "SEB Bank" },
    remittingBank: "TradeFlow Bank, Dhaka",
    collectingBank: "SEB Bank, Stockholm",
    currency: "USD",
    invoiceAmount: 248000,
    realizedAmount: 0,
    invoiceDate: "2026-04-12",
    invoiceNumber: "BKC-EXP-9921",
    blDate: "2026-04-15",
    blNumber: "MAEU-553219",
    goods: "Knit T-shirts, 64,000 pcs",
    hsCode: "6109.10",
    incoterm: "FOB Chittagong",
    countryOfDestination: "Sweden",
    portOfLoading: "Chittagong",
    portOfDischarge: "Gothenburg",
    status: "Dispatched",
    documents: [
      { id: "d1", name: "Commercial_Invoice.pdf", type: "Invoice", uploadedAt: "2026-04-15", uploadedBy: "Maker", version: 1, size: "186 KB", ocrConfidence: 0.96 },
      { id: "d2", name: "BL_MAEU553219.pdf", type: "BL", uploadedAt: "2026-04-15", uploadedBy: "Maker", version: 1, size: "201 KB", ocrConfidence: 0.93 },
      { id: "d3", name: "Packing_List.pdf", type: "Packing List", uploadedAt: "2026-04-15", uploadedBy: "Maker", version: 1, size: "84 KB" },
    ],
    compliance: [
      { id: "c1", party: "H&M Hennes & Mauritz", type: "Sanctions", result: "Clear", checkedAt: "2026-04-15" },
    ],
    swiftMessages: [
      { id: "s1", type: "MT202", status: "Sent", createdAt: "2026-04-16", reference: "EWL-2026-00031" },
    ],
    approvals: [
      { level: 1, role: "Maker", user: "F. Rahman", status: "Approved", actedAt: "2026-04-15" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-04-16" },
    ],
    audit: [
      { id: "a1", user: "F. Rahman", action: "Documents lodged for collection", timestamp: "2026-04-15 13:11" },
      { id: "a2", user: "S. Karim", action: "Dispatched via DHL AWB 1834-2210", timestamp: "2026-04-16 09:25" },
    ],
    exp: { reference: "EXP-2026-9214", amount: 248000, status: "Filed", createdAt: "2026-04-15" },
    finance: { product: "FDBP", amount: 198000, outstanding: 198000, status: "Outstanding" },
    charges: [
      { label: "Collection commission (0.10%)", amount: 248 },
      { label: "Courier (DHL)", amount: 65 },
      { label: "SWIFT", amount: 30 },
    ],
  },
  {
    id: "ewl-002",
    reference: "EWL-2026-00044",
    mode: "Documentary Collection - DA",
    exporter: { name: "Padma Leather Works Ltd.", address: "Hazaribagh, Dhaka", country: "Bangladesh" },
    buyer: { name: "Clarks International", address: "Street, Somerset", country: "United Kingdom", bank: "Barclays Bank" },
    remittingBank: "TradeFlow Bank, Dhaka",
    collectingBank: "Barclays Bank, London",
    currency: "GBP",
    invoiceAmount: 142500,
    realizedAmount: 0,
    invoiceDate: "2026-03-28",
    invoiceNumber: "PLW-EXP-7741",
    blDate: "2026-04-02",
    blNumber: "ONEY-119488",
    dueDate: "2026-07-01",
    tenorDays: 90,
    goods: "Finished leather, 18,000 sqft",
    hsCode: "4107.12",
    incoterm: "CIF Felixstowe",
    countryOfDestination: "United Kingdom",
    portOfLoading: "Chittagong",
    portOfDischarge: "Felixstowe",
    status: "Accepted",
    documents: [
      { id: "d1", name: "Invoice_PLW_7741.pdf", type: "Invoice", uploadedAt: "2026-04-02", uploadedBy: "Maker", version: 1, size: "172 KB" },
      { id: "d2", name: "BL_ONEY119488.pdf", type: "BL", uploadedAt: "2026-04-02", uploadedBy: "Maker", version: 1, size: "194 KB" },
      { id: "d3", name: "Insurance_Cert.pdf", type: "Insurance", uploadedAt: "2026-04-02", uploadedBy: "Maker", version: 1, size: "112 KB" },
    ],
    compliance: [
      { id: "c1", party: "Clarks International", type: "Sanctions", result: "Clear", checkedAt: "2026-04-03" },
    ],
    swiftMessages: [],
    approvals: [
      { level: 1, role: "Maker", user: "T. Anwar", status: "Approved", actedAt: "2026-04-02" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-04-02" },
    ],
    audit: [
      { id: "a1", user: "Barclays Bank", action: "Acceptance advice received", timestamp: "2026-04-12 15:40" },
    ],
    exp: { reference: "EXP-2026-9351", amount: 142500, status: "Filed", createdAt: "2026-04-02" },
    finance: { product: "LDBP", amount: 110000, outstanding: 110000, status: "Outstanding" },
    charges: [{ label: "Acceptance commission", amount: 285 }, { label: "Courier", amount: 60 }],
  },
  {
    id: "ewl-003",
    reference: "EWL-2026-00061",
    mode: "Advance Receipt / TT",
    exporter: { name: "Surma Jute Mills Ltd.", address: "Khulna", country: "Bangladesh" },
    buyer: { name: "Al-Futtaim Trading", address: "Dubai", country: "UAE" },
    currency: "USD",
    invoiceAmount: 56400,
    realizedAmount: 56400,
    invoiceDate: "2026-04-05",
    invoiceNumber: "SJM-PI-2210",
    goods: "Jute yarn, 80MT",
    hsCode: "5307.10",
    incoterm: "FOB Mongla",
    countryOfDestination: "UAE",
    portOfLoading: "Mongla",
    portOfDischarge: "Jebel Ali",
    status: "Realized",
    documents: [
      { id: "d1", name: "Proforma_Invoice.pdf", type: "PI", uploadedAt: "2026-04-05", uploadedBy: "Maker", version: 1, size: "78 KB" },
    ],
    compliance: [{ id: "c1", party: "Al-Futtaim Trading", type: "Sanctions", result: "Clear", checkedAt: "2026-04-06" }],
    swiftMessages: [{ id: "s1", type: "MT103", status: "ACK", createdAt: "2026-04-08", reference: "ADV-22019" }],
    approvals: [{ level: 1, role: "Maker", user: "K. Hossain", status: "Approved", actedAt: "2026-04-06" }],
    audit: [{ id: "a1", user: "K. Hossain", action: "Inward remittance credited via MT103", timestamp: "2026-04-08 11:22" }],
    exp: { reference: "EXP-2026-9420", amount: 56400, status: "Reported", createdAt: "2026-04-08" },
    realization: [{ receivedAt: "2026-04-08", amount: 56400, channel: "MT103", status: "Full" }],
    charges: [{ label: "Inward remittance commission", amount: 56.4 }],
    forexDeal: { rate: 121.65, dealId: "FX-88899", bookedAt: "2026-04-08" },
  },
  {
    id: "ewl-004",
    reference: "EWL-2026-00072",
    mode: "Open Account",
    exporter: { name: "Riverine Ceramics Ltd.", address: "Mirsarai", country: "Bangladesh" },
    buyer: { name: "Home Depot USA", address: "Atlanta, GA", country: "USA" },
    currency: "USD",
    invoiceAmount: 38900,
    realizedAmount: 0,
    invoiceDate: "2026-02-20",
    invoiceNumber: "RCL-EXP-1188",
    blDate: "2026-02-25",
    blNumber: "EGLV-220194",
    dueDate: "2026-04-26",
    tenorDays: 60,
    goods: "Ceramic tableware, 22,000 pcs",
    hsCode: "6911.10",
    incoterm: "FOB Chittagong",
    countryOfDestination: "USA",
    portOfLoading: "Chittagong",
    portOfDischarge: "Savannah",
    status: "Overdue",
    documents: [],
    compliance: [],
    swiftMessages: [],
    approvals: [],
    audit: [{ id: "a1", user: "AI Engine", action: "Realization overdue alert raised", timestamp: "2026-04-27 06:00" }],
    exp: { reference: "EXP-2026-8804", amount: 38900, status: "Pending", createdAt: "2026-02-25" },
    charges: [],
  },
];

export function getExportWoLC(id: string) {
  return exportWoLCs.find((l) => l.id === id);
}