import type { ImportLC, ExportLC } from "./lc-types";

export const importLCs: ImportLC[] = [
  {
    id: "ilc-001",
    reference: "ILC-2026-00184",
    applicant: { name: "Apex Industries Ltd.", address: "12 Industrial Zone, Dhaka", country: "Bangladesh" },
    beneficiary: { name: "Shanghai Machinery Co.", address: "88 Pudong Ave, Shanghai", country: "China", bank: "Bank of China" },
    issuingBank: "TradeFlow Bank, Dhaka",
    advisingBank: "Bank of China, Shanghai",
    currency: "USD",
    amount: 485000,
    utilized: 0,
    tolerance: 5,
    expiryDate: "2026-07-15",
    shipmentDate: "2026-06-20",
    issueDate: "2026-04-12",
    goods: "CNC milling machines, model VMX-840 (qty 6)",
    incoterm: "CIF Chittagong",
    paymentTerms: "Sight",
    status: "Issued",
    marginPercent: 15,
    marginAmount: 72750,
    charges: [
      { label: "Issuance commission", amount: 1212.5 },
      { label: "SWIFT charges", amount: 35 },
      { label: "Handling fee", amount: 150 },
    ],
    clauses: [
      { id: "c1", title: "Partial shipment", body: "Partial shipments are not allowed.", category: "Standard" },
      { id: "c2", title: "Transhipment", body: "Transhipment allowed.", category: "Standard" },
      { id: "c3", title: "Insurance", body: "Insurance covered by beneficiary, 110% CIF value.", category: "Special" },
    ],
    documents: [
      { id: "d1", name: "Proforma_Invoice_SMC.pdf", type: "PI", uploadedAt: "2026-04-10", uploadedBy: "R. Ahmed", version: 1, size: "284 KB", ocrConfidence: 0.96 },
      { id: "d2", name: "Insurance_Cover.pdf", type: "Insurance", uploadedAt: "2026-04-11", uploadedBy: "R. Ahmed", version: 1, size: "118 KB" },
    ],
    discrepancies: [],
    compliance: [
      { id: "cmp1", party: "Shanghai Machinery Co.", type: "Sanctions", result: "Clear", checkedAt: "2026-04-12" },
      { id: "cmp2", party: "Bank of China", type: "Sanctions", result: "Clear", checkedAt: "2026-04-12" },
      { id: "cmp3", party: "CNC milling machines", type: "Dual-Use Goods", result: "Flagged", checkedAt: "2026-04-12" },
    ],
    swiftMessages: [
      { id: "sw1", type: "MT700", status: "ACK", createdAt: "2026-04-12 10:24", reference: "FT26102K8821" },
    ],
    amendments: [],
    approvals: [
      { level: 1, role: "Maker", user: "R. Ahmed", status: "Approved", actedAt: "2026-04-11 14:02" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-04-12 09:18", comment: "Verified PI and limit." },
      { level: 3, role: "Trade Head", user: "M. Hossain", status: "Approved", actedAt: "2026-04-12 10:10" },
    ],
    audit: [
      { id: "a1", user: "R. Ahmed", action: "LC Created", timestamp: "2026-04-11 13:40" },
      { id: "a2", user: "S. Karim", action: "Approved (Checker)", timestamp: "2026-04-12 09:18" },
      { id: "a3", user: "System", action: "MT700 dispatched", timestamp: "2026-04-12 10:24" },
    ],
    shippingGuarantees: [],
  },
  {
    id: "ilc-002",
    reference: "ILC-2026-00185",
    applicant: { name: "Nexus Pharma BD", address: "Tongi, Gazipur", country: "Bangladesh" },
    beneficiary: { name: "BioChem GmbH", address: "Frankfurt, Germany", country: "Germany", bank: "Deutsche Bank" },
    issuingBank: "TradeFlow Bank, Dhaka",
    advisingBank: "Deutsche Bank, Frankfurt",
    currency: "EUR",
    amount: 212000,
    utilized: 212000,
    tolerance: 10,
    expiryDate: "2026-05-05",
    shipmentDate: "2026-04-18",
    issueDate: "2026-03-02",
    goods: "Pharmaceutical raw materials (API batch 22-A)",
    incoterm: "FOB Hamburg",
    paymentTerms: "Usance 90 days",
    status: "Utilized",
    marginPercent: 20,
    marginAmount: 42400,
    charges: [{ label: "Issuance commission", amount: 530 }, { label: "SWIFT charges", amount: 35 }],
    clauses: [
      { id: "c1", title: "Partial shipment", body: "Partial shipments allowed.", category: "Standard" },
    ],
    documents: [
      { id: "d1", name: "Commercial_Invoice.pdf", type: "Invoice", uploadedAt: "2026-04-19", uploadedBy: "Customer Portal", version: 1, size: "412 KB", ocrConfidence: 0.92 },
      { id: "d2", name: "Bill_of_Lading.pdf", type: "BL", uploadedAt: "2026-04-19", uploadedBy: "Customer Portal", version: 1, size: "680 KB", ocrConfidence: 0.88 },
    ],
    discrepancies: [
      { id: "ds1", type: "Late Shipment", severity: "Medium", detectedBy: "AI", remarks: "Shipment date 2026-04-22 vs LC requirement 2026-04-18.", status: "Open" },
    ],
    compliance: [
      { id: "cmp1", party: "BioChem GmbH", type: "Sanctions", result: "Clear", checkedAt: "2026-03-02" },
    ],
    swiftMessages: [
      { id: "sw1", type: "MT700", status: "ACK", createdAt: "2026-03-02 11:00", reference: "FT26061K2210" },
      { id: "sw2", type: "MT707", status: "Sent", createdAt: "2026-03-20 15:42", reference: "FT26079K3344" },
    ],
    amendments: [
      { id: "am1", field: "Shipment Date", oldValue: "2026-04-10", newValue: "2026-04-18", status: "Approved", requestedAt: "2026-03-19", approver: "S. Karim" },
    ],
    approvals: [
      { level: 1, role: "Maker", user: "T. Rahman", status: "Approved", actedAt: "2026-03-01 12:00" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-03-02 10:30" },
    ],
    audit: [
      { id: "a1", user: "T. Rahman", action: "LC Created", timestamp: "2026-03-01 12:00" },
      { id: "a2", user: "System", action: "MT700 dispatched", timestamp: "2026-03-02 11:00" },
      { id: "a3", user: "Customer Portal", action: "Documents uploaded", timestamp: "2026-04-19 09:14" },
    ],
    shippingGuarantees: [
      { id: "sg1", reference: "SG-2026-0044", amount: 212000, expiry: "2026-05-30", status: "Active" },
    ],
    imp: { reference: "IMP-2026-0091", amount: 212000, status: "Pending Approval", createdAt: "2026-04-20" },
  },
  {
    id: "ilc-003",
    reference: "ILC-2026-00186",
    applicant: { name: "GreenAgro Foods", address: "Bogura, BD", country: "Bangladesh" },
    beneficiary: { name: "Sun Valley Grains", address: "Sacramento, USA", country: "USA", bank: "Wells Fargo" },
    issuingBank: "TradeFlow Bank, Dhaka",
    advisingBank: "Wells Fargo, San Francisco",
    currency: "USD",
    amount: 96000,
    utilized: 0,
    tolerance: 5,
    expiryDate: "2026-08-01",
    shipmentDate: "2026-07-10",
    issueDate: "",
    goods: "Soybean meal, 200 MT",
    incoterm: "CFR Chittagong",
    paymentTerms: "Sight",
    status: "Submitted",
    marginPercent: 10,
    marginAmount: 9600,
    charges: [{ label: "Issuance commission", amount: 240 }],
    clauses: [],
    documents: [
      { id: "d1", name: "PI_SunValley.pdf", type: "PI", uploadedAt: "2026-04-22", uploadedBy: "Customer Portal", version: 1, size: "210 KB", ocrConfidence: 0.94 },
    ],
    discrepancies: [],
    compliance: [],
    swiftMessages: [],
    amendments: [],
    approvals: [
      { level: 1, role: "Maker", user: "R. Ahmed", status: "Approved", actedAt: "2026-04-22 16:00" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Pending" },
    ],
    audit: [
      { id: "a1", user: "Customer Portal", action: "Draft submitted", timestamp: "2026-04-22 15:30" },
    ],
    shippingGuarantees: [],
  },
  {
    id: "ilc-004",
    reference: "ILC-2026-00187",
    applicant: { name: "Steelworks Ltd.", address: "Narayanganj, BD", country: "Bangladesh" },
    beneficiary: { name: "Posco Trading", address: "Seoul, Korea", country: "South Korea", bank: "KEB Hana Bank" },
    issuingBank: "TradeFlow Bank, Dhaka",
    advisingBank: "KEB Hana Bank, Seoul",
    currency: "USD",
    amount: 1250000,
    utilized: 600000,
    tolerance: 10,
    expiryDate: "2026-09-30",
    shipmentDate: "2026-09-01",
    issueDate: "2026-02-15",
    goods: "Hot-rolled steel coils, 800 MT",
    incoterm: "CIF Chittagong",
    paymentTerms: "Usance 180 days",
    status: "Issued",
    marginPercent: 25,
    marginAmount: 312500,
    charges: [{ label: "Issuance commission", amount: 3125 }, { label: "SWIFT charges", amount: 35 }],
    clauses: [
      { id: "c1", title: "Partial shipment", body: "Partial shipments allowed.", category: "Standard" },
    ],
    documents: [],
    discrepancies: [],
    compliance: [
      { id: "cmp1", party: "Posco Trading", type: "Sanctions", result: "Clear", checkedAt: "2026-02-15" },
    ],
    swiftMessages: [{ id: "sw1", type: "MT700", status: "ACK", createdAt: "2026-02-15 12:00", reference: "FT26046K1100" }],
    amendments: [],
    approvals: [
      { level: 1, role: "Maker", user: "T. Rahman", status: "Approved", actedAt: "2026-02-14" },
      { level: 2, role: "Checker", user: "S. Karim", status: "Approved", actedAt: "2026-02-15" },
      { level: 3, role: "Trade Head", user: "M. Hossain", status: "Approved", actedAt: "2026-02-15" },
    ],
    audit: [],
    shippingGuarantees: [],
  },
  {
    id: "ilc-005",
    reference: "ILC-2025-00912",
    applicant: { name: "Ocean Textiles", address: "Savar, BD", country: "Bangladesh" },
    beneficiary: { name: "Cotton Fields Inc.", address: "Memphis, USA", country: "USA" },
    issuingBank: "TradeFlow Bank, Dhaka",
    advisingBank: "Citibank, Memphis",
    currency: "USD",
    amount: 340000,
    utilized: 340000,
    tolerance: 5,
    expiryDate: "2025-12-15",
    shipmentDate: "2025-11-20",
    issueDate: "2025-09-01",
    goods: "Raw cotton, 150 bales",
    incoterm: "CIF Chittagong",
    paymentTerms: "Sight",
    status: "Closed",
    marginPercent: 15,
    marginAmount: 51000,
    charges: [],
    clauses: [],
    documents: [],
    discrepancies: [],
    compliance: [],
    swiftMessages: [],
    amendments: [],
    approvals: [],
    audit: [],
    shippingGuarantees: [],
  },
];

export const exportLCs: ExportLC[] = [
  {
    id: "elc-001",
    reference: "ELC-2026-00072",
    beneficiary: { name: "Bay Garments Ltd.", address: "Ashulia, BD", country: "Bangladesh" },
    applicant: { name: "H&M International", address: "Stockholm, Sweden", country: "Sweden" },
    issuingBank: "Nordea Bank, Stockholm",
    advisingBank: "TradeFlow Bank, Dhaka",
    currency: "EUR",
    amount: 680000,
    utilized: 200000,
    expiryDate: "2026-08-25",
    shipmentDate: "2026-08-01",
    adviceDate: "2026-04-05",
    goods: "Knitwear, 40,000 pcs",
    status: "Issued",
    lienAmount: 680000,
    documents: [
      { id: "d1", name: "Commercial_Invoice_BG.pdf", type: "Invoice", uploadedAt: "2026-04-18", uploadedBy: "L. Nahar", version: 1, size: "320 KB" },
      { id: "d2", name: "BL_Bay_Garments.pdf", type: "BL", uploadedAt: "2026-04-18", uploadedBy: "L. Nahar", version: 1, size: "514 KB" },
    ],
    discrepancies: [],
    swiftMessages: [{ id: "sw1", type: "MT710", status: "ACK", createdAt: "2026-04-05 09:30", reference: "FT26095K8801" }],
    audit: [
      { id: "a1", user: "System", action: "MT710 received and parsed", timestamp: "2026-04-05 09:30" },
      { id: "a2", user: "L. Nahar", action: "LC advised to beneficiary", timestamp: "2026-04-05 11:14" },
    ],
    transfers: [],
    finance: [
      { id: "f1", product: "PC", amount: 150000, status: "Active", outstanding: 150000 },
    ],
    forwarding: { bank: "Nordea Bank", courier: "DHL", awb: "DHL-991-2284", dispatchedAt: "2026-04-19" },
    realization: [{ receivedAt: "2026-04-22", amount: 200000, status: "Partial" }],
  },
  {
    id: "elc-002",
    reference: "ELC-2026-00073",
    beneficiary: { name: "Padma Leather Goods", address: "Hazaribagh, BD", country: "Bangladesh" },
    applicant: { name: "Italmoda SpA", address: "Milan, Italy", country: "Italy" },
    issuingBank: "UniCredit, Milan",
    advisingBank: "TradeFlow Bank, Dhaka",
    currency: "USD",
    amount: 245000,
    utilized: 0,
    expiryDate: "2026-07-30",
    shipmentDate: "2026-07-10",
    adviceDate: "2026-04-15",
    goods: "Finished leather goods, mixed assortment",
    status: "Approved",
    lienAmount: 245000,
    documents: [],
    discrepancies: [],
    swiftMessages: [{ id: "sw1", type: "MT710", status: "Sent", createdAt: "2026-04-15 14:00", reference: "FT26105K0102" }],
    audit: [],
    transfers: [
      { id: "tr1", transferee: "Padma Tannery (Sub-supplier)", amount: 80000, type: "Partial", date: "2026-04-17" },
    ],
    backToBack: { reference: "ILC-2026-00190", amount: 120000, status: "Issued" },
    finance: [],
    realization: [],
  },
  {
    id: "elc-003",
    reference: "ELC-2026-00074",
    beneficiary: { name: "Sundarban Crafts", address: "Khulna, BD", country: "Bangladesh" },
    applicant: { name: "Tokyo Gifts Co.", address: "Tokyo, Japan", country: "Japan" },
    issuingBank: "MUFG Bank, Tokyo",
    advisingBank: "TradeFlow Bank, Dhaka",
    currency: "JPY",
    amount: 8500000,
    utilized: 0,
    expiryDate: "2026-06-20",
    shipmentDate: "2026-06-01",
    adviceDate: "2026-04-20",
    goods: "Handicraft samples — FOC",
    status: "Submitted",
    lienAmount: 0,
    documents: [],
    discrepancies: [],
    swiftMessages: [],
    audit: [],
    transfers: [],
    finance: [],
    realization: [],
    isFOC: true,
  },
];

export function getImportLC(id: string): ImportLC | undefined {
  return importLCs.find((l) => l.id === id || l.reference === id);
}

export function getExportLC(id: string): ExportLC | undefined {
  return exportLCs.find((l) => l.id === id || l.reference === id);
}