/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportWoLcIndexRouteImport } from './routes/import-wo-lc.index'
import { Route as ImportLcIndexRouteImport } from './routes/import-lc.index'
import { Route as GuaranteesIndexRouteImport } from './routes/guarantees.index'
import { Route as ExportWoLcIndexRouteImport } from './routes/export-wo-lc.index'
import { Route as ExportLcIndexRouteImport } from './routes/export-lc.index'
import { Route as ImportWoLcNewRouteImport } from './routes/import-wo-lc.new'
import { Route as ImportWoLcIdRouteImport } from './routes/import-wo-lc.$id'
import { Route as ImportLcNewRouteImport } from './routes/import-lc.new'
import { Route as ImportLcIdRouteImport } from './routes/import-lc.$id'
import { Route as ExportWoLcNewRouteImport } from './routes/export-wo-lc.new'
import { Route as ExportWoLcIdRouteImport } from './routes/export-wo-lc.$id'
import { Route as ExportLcNewRouteImport } from './routes/export-lc.new'
import { Route as ExportLcIdRouteImport } from './routes/export-lc.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWoLcIndexRoute = ImportWoLcIndexRouteImport.update({
  id: '/import-wo-lc/',
  path: '/import-wo-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportLcIndexRoute = ImportLcIndexRouteImport.update({
  id: '/import-lc/',
  path: '/import-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteesIndexRoute = GuaranteesIndexRouteImport.update({
  id: '/guarantees/',
  path: '/guarantees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportWoLcIndexRoute = ExportWoLcIndexRouteImport.update({
  id: '/export-wo-lc/',
  path: '/export-wo-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportLcIndexRoute = ExportLcIndexRouteImport.update({
  id: '/export-lc/',
  path: '/export-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWoLcNewRoute = ImportWoLcNewRouteImport.update({
  id: '/import-wo-lc/new',
  path: '/import-wo-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWoLcIdRoute = ImportWoLcIdRouteImport.update({
  id: '/import-wo-lc/$id',
  path: '/import-wo-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportLcNewRoute = ImportLcNewRouteImport.update({
  id: '/import-lc/new',
  path: '/import-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportLcIdRoute = ImportLcIdRouteImport.update({
  id: '/import-lc/$id',
  path: '/import-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportWoLcNewRoute = ExportWoLcNewRouteImport.update({
  id: '/export-wo-lc/new',
  path: '/export-wo-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportWoLcIdRoute = ExportWoLcIdRouteImport.update({
  id: '/export-wo-lc/$id',
  path: '/export-wo-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportLcNewRoute = ExportLcNewRouteImport.update({
  id: '/export-lc/new',
  path: '/export-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportLcIdRoute = ExportLcIdRouteImport.update({
  id: '/export-lc/$id',
  path: '/export-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export-lc/$id': typeof ExportLcIdRoute
  '/export-lc/new': typeof ExportLcNewRoute
  '/export-wo-lc/$id': typeof ExportWoLcIdRoute
  '/export-wo-lc/new': typeof ExportWoLcNewRoute
  '/import-lc/$id': typeof ImportLcIdRoute
  '/import-lc/new': typeof ImportLcNewRoute
  '/import-wo-lc/$id': typeof ImportWoLcIdRoute
  '/import-wo-lc/new': typeof ImportWoLcNewRoute
  '/export-lc/': typeof ExportLcIndexRoute
  '/export-wo-lc/': typeof ExportWoLcIndexRoute
  '/guarantees/': typeof GuaranteesIndexRoute
  '/import-lc/': typeof ImportLcIndexRoute
  '/import-wo-lc/': typeof ImportWoLcIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export-lc/$id': typeof ExportLcIdRoute
  '/export-lc/new': typeof ExportLcNewRoute
  '/export-wo-lc/$id': typeof ExportWoLcIdRoute
  '/export-wo-lc/new': typeof ExportWoLcNewRoute
  '/import-lc/$id': typeof ImportLcIdRoute
  '/import-lc/new': typeof ImportLcNewRoute
  '/import-wo-lc/$id': typeof ImportWoLcIdRoute
  '/import-wo-lc/new': typeof ImportWoLcNewRoute
  '/export-lc': typeof ExportLcIndexRoute
  '/export-wo-lc': typeof ExportWoLcIndexRoute
  '/guarantees': typeof GuaranteesIndexRoute
  '/import-lc': typeof ImportLcIndexRoute
  '/import-wo-lc': typeof ImportWoLcIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export-lc/$id': typeof ExportLcIdRoute
  '/export-lc/new': typeof ExportLcNewRoute
  '/export-wo-lc/$id': typeof ExportWoLcIdRoute
  '/export-wo-lc/new': typeof ExportWoLcNewRoute
  '/import-lc/$id': typeof ImportLcIdRoute
  '/import-lc/new': typeof ImportLcNewRoute
  '/import-wo-lc/$id': typeof ImportWoLcIdRoute
  '/import-wo-lc/new': typeof ImportWoLcNewRoute
  '/export-lc/': typeof ExportLcIndexRoute
  '/export-wo-lc/': typeof ExportWoLcIndexRoute
  '/guarantees/': typeof GuaranteesIndexRoute
  '/import-lc/': typeof ImportLcIndexRoute
  '/import-wo-lc/': typeof ImportWoLcIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export-lc/$id'
    | '/export-lc/new'
    | '/export-wo-lc/$id'
    | '/export-wo-lc/new'
    | '/import-lc/$id'
    | '/import-lc/new'
    | '/import-wo-lc/$id'
    | '/import-wo-lc/new'
    | '/export-lc/'
    | '/export-wo-lc/'
    | '/guarantees/'
    | '/import-lc/'
    | '/import-wo-lc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export-lc/$id'
    | '/export-lc/new'
    | '/export-wo-lc/$id'
    | '/export-wo-lc/new'
    | '/import-lc/$id'
    | '/import-lc/new'
    | '/import-wo-lc/$id'
    | '/import-wo-lc/new'
    | '/export-lc'
    | '/export-wo-lc'
    | '/guarantees'
    | '/import-lc'
    | '/import-wo-lc'
  id:
    | '__root__'
    | '/'
    | '/export-lc/$id'
    | '/export-lc/new'
    | '/export-wo-lc/$id'
    | '/export-wo-lc/new'
    | '/import-lc/$id'
    | '/import-lc/new'
    | '/import-wo-lc/$id'
    | '/import-wo-lc/new'
    | '/export-lc/'
    | '/export-wo-lc/'
    | '/guarantees/'
    | '/import-lc/'
    | '/import-wo-lc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportLcIdRoute: typeof ExportLcIdRoute
  ExportLcNewRoute: typeof ExportLcNewRoute
  ExportWoLcIdRoute: typeof ExportWoLcIdRoute
  ExportWoLcNewRoute: typeof ExportWoLcNewRoute
  ImportLcIdRoute: typeof ImportLcIdRoute
  ImportLcNewRoute: typeof ImportLcNewRoute
  ImportWoLcIdRoute: typeof ImportWoLcIdRoute
  ImportWoLcNewRoute: typeof ImportWoLcNewRoute
  ExportLcIndexRoute: typeof ExportLcIndexRoute
  ExportWoLcIndexRoute: typeof ExportWoLcIndexRoute
  GuaranteesIndexRoute: typeof GuaranteesIndexRoute
  ImportLcIndexRoute: typeof ImportLcIndexRoute
  ImportWoLcIndexRoute: typeof ImportWoLcIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-wo-lc/': {
      id: '/import-wo-lc/'
      path: '/import-wo-lc'
      fullPath: '/import-wo-lc/'
      preLoaderRoute: typeof ImportWoLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-lc/': {
      id: '/import-lc/'
      path: '/import-lc'
      fullPath: '/import-lc/'
      preLoaderRoute: typeof ImportLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantees/': {
      id: '/guarantees/'
      path: '/guarantees'
      fullPath: '/guarantees/'
      preLoaderRoute: typeof GuaranteesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-wo-lc/': {
      id: '/export-wo-lc/'
      path: '/export-wo-lc'
      fullPath: '/export-wo-lc/'
      preLoaderRoute: typeof ExportWoLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-lc/': {
      id: '/export-lc/'
      path: '/export-lc'
      fullPath: '/export-lc/'
      preLoaderRoute: typeof ExportLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-wo-lc/new': {
      id: '/import-wo-lc/new'
      path: '/import-wo-lc/new'
      fullPath: '/import-wo-lc/new'
      preLoaderRoute: typeof ImportWoLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-wo-lc/$id': {
      id: '/import-wo-lc/$id'
      path: '/import-wo-lc/$id'
      fullPath: '/import-wo-lc/$id'
      preLoaderRoute: typeof ImportWoLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-lc/new': {
      id: '/import-lc/new'
      path: '/import-lc/new'
      fullPath: '/import-lc/new'
      preLoaderRoute: typeof ImportLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-lc/$id': {
      id: '/import-lc/$id'
      path: '/import-lc/$id'
      fullPath: '/import-lc/$id'
      preLoaderRoute: typeof ImportLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-wo-lc/new': {
      id: '/export-wo-lc/new'
      path: '/export-wo-lc/new'
      fullPath: '/export-wo-lc/new'
      preLoaderRoute: typeof ExportWoLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-wo-lc/$id': {
      id: '/export-wo-lc/$id'
      path: '/export-wo-lc/$id'
      fullPath: '/export-wo-lc/$id'
      preLoaderRoute: typeof ExportWoLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-lc/new': {
      id: '/export-lc/new'
      path: '/export-lc/new'
      fullPath: '/export-lc/new'
      preLoaderRoute: typeof ExportLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-lc/$id': {
      id: '/export-lc/$id'
      path: '/export-lc/$id'
      fullPath: '/export-lc/$id'
      preLoaderRoute: typeof ExportLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportLcIdRoute: ExportLcIdRoute,
  ExportLcNewRoute: ExportLcNewRoute,
  ExportWoLcIdRoute: ExportWoLcIdRoute,
  ExportWoLcNewRoute: ExportWoLcNewRoute,
  ImportLcIdRoute: ImportLcIdRoute,
  ImportLcNewRoute: ImportLcNewRoute,
  ImportWoLcIdRoute: ImportWoLcIdRoute,
  ImportWoLcNewRoute: ImportWoLcNewRoute,
  ExportLcIndexRoute: ExportLcIndexRoute,
  ExportWoLcIndexRoute: ExportWoLcIndexRoute,
  GuaranteesIndexRoute: GuaranteesIndexRoute,
  ImportLcIndexRoute: ImportLcIndexRoute,
  ImportWoLcIndexRoute: ImportWoLcIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
