/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SwiftIndexRouteImport } from './routes/swift.index'
import { Route as ReportingIndexRouteImport } from './routes/reporting.index'
import { Route as ImportWoLcIndexRouteImport } from './routes/import-wo-lc.index'
import { Route as ImportLcIndexRouteImport } from './routes/import-lc.index'
import { Route as GuaranteesIndexRouteImport } from './routes/guarantees.index'
import { Route as ExportWoLcIndexRouteImport } from './routes/export-wo-lc.index'
import { Route as ExportLcIndexRouteImport } from './routes/export-lc.index'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ImportWoLcNewRouteImport } from './routes/import-wo-lc.new'
import { Route as ImportWoLcIdRouteImport } from './routes/import-wo-lc.$id'
import { Route as ImportLcNewRouteImport } from './routes/import-lc.new'
import { Route as ImportLcIdRouteImport } from './routes/import-lc.$id'
import { Route as GuaranteesNewRouteImport } from './routes/guarantees.new'
import { Route as GuaranteesIdRouteImport } from './routes/guarantees.$id'
import { Route as ExportWoLcNewRouteImport } from './routes/export-wo-lc.new'
import { Route as ExportWoLcIdRouteImport } from './routes/export-wo-lc.$id'
import { Route as ExportLcIdRouteImport } from './routes/export-lc.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SwiftIndexRoute = SwiftIndexRouteImport.update({
  id: '/swift/',
  path: '/swift/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingIndexRoute = ReportingIndexRouteImport.update({
  id: '/reporting/',
  path: '/reporting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWoLcIndexRoute = ImportWoLcIndexRouteImport.update({
  id: '/import-wo-lc/',
  path: '/import-wo-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportLcIndexRoute = ImportLcIndexRouteImport.update({
  id: '/import-lc/',
  path: '/import-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteesIndexRoute = GuaranteesIndexRouteImport.update({
  id: '/guarantees/',
  path: '/guarantees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportWoLcIndexRoute = ExportWoLcIndexRouteImport.update({
  id: '/export-wo-lc/',
  path: '/export-wo-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportLcIndexRoute = ExportLcIndexRouteImport.update({
  id: '/export-lc/',
  path: '/export-lc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWoLcNewRoute = ImportWoLcNewRouteImport.update({
  id: '/import-wo-lc/new',
  path: '/import-wo-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportWoLcIdRoute = ImportWoLcIdRouteImport.update({
  id: '/import-wo-lc/$id',
  path: '/import-wo-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportLcNewRoute = ImportLcNewRouteImport.update({
  id: '/import-lc/new',
  path: '/import-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportLcIdRoute = ImportLcIdRouteImport.update({
  id: '/import-lc/$id',
  path: '/import-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteesNewRoute = GuaranteesNewRouteImport.update({
  id: '/guarantees/new',
  path: '/guarantees/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteesIdRoute = GuaranteesIdRouteImport.update({
  id: '/guarantees/$id',
  path: '/guarantees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportWoLcNewRoute = ExportWoLcNewRouteImport.update({
  id: '/export-wo-lc/new',
  path: '/export-wo-lc/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportWoLcIdRoute = ExportWoLcIdRouteImport.update({
  id: '/export-wo-lc/$id',
  path: '/export-wo-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportLcIdRoute = ExportLcIdRouteImport.update({
  id: '/export-lc/$id',
  path: '/export-lc/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export-lc/$id': typeof ExportLcIdRoute
  '/export-wo-lc/$id': typeof ExportWoLcIdRoute
  '/export-wo-lc/new': typeof ExportWoLcNewRoute
  '/guarantees/$id': typeof GuaranteesIdRoute
  '/guarantees/new': typeof GuaranteesNewRoute
  '/import-lc/$id': typeof ImportLcIdRoute
  '/import-lc/new': typeof ImportLcNewRoute
  '/import-wo-lc/$id': typeof ImportWoLcIdRoute
  '/import-wo-lc/new': typeof ImportWoLcNewRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/export-lc/': typeof ExportLcIndexRoute
  '/export-wo-lc/': typeof ExportWoLcIndexRoute
  '/guarantees/': typeof GuaranteesIndexRoute
  '/import-lc/': typeof ImportLcIndexRoute
  '/import-wo-lc/': typeof ImportWoLcIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/swift/': typeof SwiftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export-lc/$id': typeof ExportLcIdRoute
  '/export-wo-lc/$id': typeof ExportWoLcIdRoute
  '/export-wo-lc/new': typeof ExportWoLcNewRoute
  '/guarantees/$id': typeof GuaranteesIdRoute
  '/guarantees/new': typeof GuaranteesNewRoute
  '/import-lc/$id': typeof ImportLcIdRoute
  '/import-lc/new': typeof ImportLcNewRoute
  '/import-wo-lc/$id': typeof ImportWoLcIdRoute
  '/import-wo-lc/new': typeof ImportWoLcNewRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/export-lc': typeof ExportLcIndexRoute
  '/export-wo-lc': typeof ExportWoLcIndexRoute
  '/guarantees': typeof GuaranteesIndexRoute
  '/import-lc': typeof ImportLcIndexRoute
  '/import-wo-lc': typeof ImportWoLcIndexRoute
  '/reporting': typeof ReportingIndexRoute
  '/swift': typeof SwiftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/export-lc/$id': typeof ExportLcIdRoute
  '/export-wo-lc/$id': typeof ExportWoLcIdRoute
  '/export-wo-lc/new': typeof ExportWoLcNewRoute
  '/guarantees/$id': typeof GuaranteesIdRoute
  '/guarantees/new': typeof GuaranteesNewRoute
  '/import-lc/$id': typeof ImportLcIdRoute
  '/import-lc/new': typeof ImportLcNewRoute
  '/import-wo-lc/$id': typeof ImportWoLcIdRoute
  '/import-wo-lc/new': typeof ImportWoLcNewRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/export-lc/': typeof ExportLcIndexRoute
  '/export-wo-lc/': typeof ExportWoLcIndexRoute
  '/guarantees/': typeof GuaranteesIndexRoute
  '/import-lc/': typeof ImportLcIndexRoute
  '/import-wo-lc/': typeof ImportWoLcIndexRoute
  '/reporting/': typeof ReportingIndexRoute
  '/swift/': typeof SwiftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/export-lc/$id'
    | '/export-wo-lc/$id'
    | '/export-wo-lc/new'
    | '/guarantees/$id'
    | '/guarantees/new'
    | '/import-lc/$id'
    | '/import-lc/new'
    | '/import-wo-lc/$id'
    | '/import-wo-lc/new'
    | '/connectors/'
    | '/export-lc/'
    | '/export-wo-lc/'
    | '/guarantees/'
    | '/import-lc/'
    | '/import-wo-lc/'
    | '/reporting/'
    | '/swift/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/export-lc/$id'
    | '/export-wo-lc/$id'
    | '/export-wo-lc/new'
    | '/guarantees/$id'
    | '/guarantees/new'
    | '/import-lc/$id'
    | '/import-lc/new'
    | '/import-wo-lc/$id'
    | '/import-wo-lc/new'
    | '/connectors'
    | '/export-lc'
    | '/export-wo-lc'
    | '/guarantees'
    | '/import-lc'
    | '/import-wo-lc'
    | '/reporting'
    | '/swift'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/export-lc/$id'
    | '/export-wo-lc/$id'
    | '/export-wo-lc/new'
    | '/guarantees/$id'
    | '/guarantees/new'
    | '/import-lc/$id'
    | '/import-lc/new'
    | '/import-wo-lc/$id'
    | '/import-wo-lc/new'
    | '/connectors/'
    | '/export-lc/'
    | '/export-wo-lc/'
    | '/guarantees/'
    | '/import-lc/'
    | '/import-wo-lc/'
    | '/reporting/'
    | '/swift/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExportLcIdRoute: typeof ExportLcIdRoute
  ExportWoLcIdRoute: typeof ExportWoLcIdRoute
  ExportWoLcNewRoute: typeof ExportWoLcNewRoute
  GuaranteesIdRoute: typeof GuaranteesIdRoute
  GuaranteesNewRoute: typeof GuaranteesNewRoute
  ImportLcIdRoute: typeof ImportLcIdRoute
  ImportLcNewRoute: typeof ImportLcNewRoute
  ImportWoLcIdRoute: typeof ImportWoLcIdRoute
  ImportWoLcNewRoute: typeof ImportWoLcNewRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  ExportLcIndexRoute: typeof ExportLcIndexRoute
  ExportWoLcIndexRoute: typeof ExportWoLcIndexRoute
  GuaranteesIndexRoute: typeof GuaranteesIndexRoute
  ImportLcIndexRoute: typeof ImportLcIndexRoute
  ImportWoLcIndexRoute: typeof ImportWoLcIndexRoute
  ReportingIndexRoute: typeof ReportingIndexRoute
  SwiftIndexRoute: typeof SwiftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swift/': {
      id: '/swift/'
      path: '/swift'
      fullPath: '/swift/'
      preLoaderRoute: typeof SwiftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting/': {
      id: '/reporting/'
      path: '/reporting'
      fullPath: '/reporting/'
      preLoaderRoute: typeof ReportingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-wo-lc/': {
      id: '/import-wo-lc/'
      path: '/import-wo-lc'
      fullPath: '/import-wo-lc/'
      preLoaderRoute: typeof ImportWoLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-lc/': {
      id: '/import-lc/'
      path: '/import-lc'
      fullPath: '/import-lc/'
      preLoaderRoute: typeof ImportLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantees/': {
      id: '/guarantees/'
      path: '/guarantees'
      fullPath: '/guarantees/'
      preLoaderRoute: typeof GuaranteesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-wo-lc/': {
      id: '/export-wo-lc/'
      path: '/export-wo-lc'
      fullPath: '/export-wo-lc/'
      preLoaderRoute: typeof ExportWoLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-lc/': {
      id: '/export-lc/'
      path: '/export-lc'
      fullPath: '/export-lc/'
      preLoaderRoute: typeof ExportLcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-wo-lc/new': {
      id: '/import-wo-lc/new'
      path: '/import-wo-lc/new'
      fullPath: '/import-wo-lc/new'
      preLoaderRoute: typeof ImportWoLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-wo-lc/$id': {
      id: '/import-wo-lc/$id'
      path: '/import-wo-lc/$id'
      fullPath: '/import-wo-lc/$id'
      preLoaderRoute: typeof ImportWoLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-lc/new': {
      id: '/import-lc/new'
      path: '/import-lc/new'
      fullPath: '/import-lc/new'
      preLoaderRoute: typeof ImportLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-lc/$id': {
      id: '/import-lc/$id'
      path: '/import-lc/$id'
      fullPath: '/import-lc/$id'
      preLoaderRoute: typeof ImportLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantees/new': {
      id: '/guarantees/new'
      path: '/guarantees/new'
      fullPath: '/guarantees/new'
      preLoaderRoute: typeof GuaranteesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantees/$id': {
      id: '/guarantees/$id'
      path: '/guarantees/$id'
      fullPath: '/guarantees/$id'
      preLoaderRoute: typeof GuaranteesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-wo-lc/new': {
      id: '/export-wo-lc/new'
      path: '/export-wo-lc/new'
      fullPath: '/export-wo-lc/new'
      preLoaderRoute: typeof ExportWoLcNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-wo-lc/$id': {
      id: '/export-wo-lc/$id'
      path: '/export-wo-lc/$id'
      fullPath: '/export-wo-lc/$id'
      preLoaderRoute: typeof ExportWoLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-lc/$id': {
      id: '/export-lc/$id'
      path: '/export-lc/$id'
      fullPath: '/export-lc/$id'
      preLoaderRoute: typeof ExportLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExportLcIdRoute: ExportLcIdRoute,
  ExportWoLcIdRoute: ExportWoLcIdRoute,
  ExportWoLcNewRoute: ExportWoLcNewRoute,
  GuaranteesIdRoute: GuaranteesIdRoute,
  GuaranteesNewRoute: GuaranteesNewRoute,
  ImportLcIdRoute: ImportLcIdRoute,
  ImportLcNewRoute: ImportLcNewRoute,
  ImportWoLcIdRoute: ImportWoLcIdRoute,
  ImportWoLcNewRoute: ImportWoLcNewRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  ExportLcIndexRoute: ExportLcIndexRoute,
  ExportWoLcIndexRoute: ExportWoLcIndexRoute,
  GuaranteesIndexRoute: GuaranteesIndexRoute,
  ImportLcIndexRoute: ImportLcIndexRoute,
  ImportWoLcIndexRoute: ImportWoLcIndexRoute,
  ReportingIndexRoute: ReportingIndexRoute,
  SwiftIndexRoute: SwiftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
